image:
- Visual Studio 2019
init: 
- tzutil /s "Central Europe Standard Time"
install:
- cd %APPVEYOR_BUILD_FOLDER%
- git submodule update --init --recursive
services:
- mssql2017
build_script:
- cmd: dotnet tool restore
- ps: .\Source\Breeze.NHibernate.NorthwindIB.Tests.Models\Databases\updateFromHere.ps1 -Connection "(local)\SQL2017"
test_script:
- cmd: dotnet cake --target=test-northwind