namespace Breeze.NHibernate.Metadata
{
    public enum AutoGeneratedKeyType
    {
        /// <summary>
        /// Key is not autogenerated.
        /// </summary>
        None,

        /// <summary>
        /// Key is automatically generated on the database server.
        /// </summary>
        Identity,

        /// <summary>
        /// Key is generated by an IKeyGenerator implementation on the server.
        /// </summary>
        KeyGenerator
    }
}
