using Breeze.NHibernate.Metadata;

namespace Breeze.NHibernate
{
    /// <summary>
    /// Represent an auto-generated property.
    /// </summary>
    public class AutoGeneratedKey
    {
        /// <summary>
        /// The auto-generated key type.
        /// </summary>
        public AutoGeneratedKeyType AutoGeneratedKeyType { get; set; }

        /// <summary>
        /// The auto-generated property name.
        /// </summary>
        public string PropertyName { get; set; }
    }
}
