
namespace Breeze.NHibernate
{
    /// <summary>
    /// Contains the client and server side key values for an entity when the key is auto-generated.
    /// </summary>
    public class KeyMapping
    {
        /// <summary>
        /// Constructs an instance of <see cref="KeyMapping"/>.
        /// </summary>
        public KeyMapping(string entityTypeName, object tempValue, object realValue)
        {
            EntityTypeName = entityTypeName;
            TempValue = tempValue;
            RealValue = realValue;
        }

        /// <summary>
        /// The Entity type name
        /// </summary>
        public string EntityTypeName { get; }

        /// <summary>
        /// The key generated by the client.
        /// </summary>
        public object TempValue { get; }

        /// <summary>
        /// The key generated by the database or NHibernate.
        /// </summary>
        public object RealValue { get; }
    }
}
